on:
  workflow_dispatch:
  push:

jobs:
  job1:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.matrix.outputs.matrix }}
    steps:
      - id: matrix
        run: |
          if [[ ${{ github.event_name }} == 'workflow_dispatch' ]]; then
            echo "::set-output name=matrix::['BABEL_3_X_DEV']"
          elif [[ true ]]; then
            echo "::set-output name=matrix::['BABEL_3_X_DEV', 'BABEL_2_X_DEV']"
          fi

  job2:
    needs: [ job1 ]
    runs-on: ubuntu-latest
    strategy:
      matrix:
        branch: ${{fromJson(needs.job1.outputs.matrix)}}
    steps:
      - run: |
          extensions=( babelfishpg_tsql babelfishpg_tds babelfishpg_common babelfishpg_money )
          for (( i=0; i<4; i++ )); do
            echo ${varlist[$i]}
          done


  # job3:
  #   needs: [ job1 ]
  #   runs-on: ubuntu-latest
  #   strategy:
  #     matrix:
  #       value: ${{fromJson(needs.job1.outputs.last)}}
  #   steps:
  #     - run: |
  #         echo Current: "${{ matrix.value }}"